In [2]:
import torch
import numpy as np

In [158]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [6]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]]) 
print(x * 10)

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])


In [10]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]]) 
y = x + 10
print(y)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])


In [18]:
y = torch.tensor([2, 3, 1, 0]) # y.shape == (4)
print(f'value: {y}, shape: {y.shape}')

y = y.view(4, 1)                # y.shape == (4, 1)
print(f'value: {y}, shape: {y.shape}')

y = y.reshape(4, 1)
print(f'value: {y}, shape: {y.shape}')

value: tensor([2, 3, 1, 0]), shape: torch.Size([4])
value: tensor([[2],
        [3],
        [1],
        [0]]), shape: torch.Size([4, 1])
value: tensor([[2],
        [3],
        [1],
        [0]]), shape: torch.Size([4, 1])


In [51]:
x = torch.randn(size=(1, 3, 1))
x

tensor([[[-0.6784],
         [-0.9309],
         [ 0.2471]]])

In [55]:
x.reshape(3)

tensor([-0.6784, -0.9309,  0.2471])

In [56]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
print(torch.matmul(x, y))

tensor([[11],
        [35]])


In [102]:
torch.random.manual_seed(seed=42)
x = torch.randint(low=1, high=10, size=(1, 3, 2))
x.squeeze()

tensor([[[7, 6],
         [8, 5],
         [1, 3]]])

In [138]:
torch.random.manual_seed(12)
A = torch.randint(low=1, high=20, size=(3, 4), dtype=torch.int32)
print(A)

get_max = A.max(axis=-1, keepdim=True)
print(get_max.values)
print(get_max.indices)

tensor([[14, 15,  9, 19],
        [13, 13, 14, 10],
        [12, 13, 13,  5]], dtype=torch.int32)
tensor([[19],
        [14],
        [13]], dtype=torch.int32)
tensor([[3],
        [2],
        [1]])


In [141]:
help(torch.Tensor.reshape)

Help on method_descriptor:

reshape(...)
    reshape(*shape) -> Tensor
    
    Returns a tensor with the same data and number of elements as :attr:`self`
    but with the specified shape. This method returns a view if :attr:`shape` is
    compatible with the current shape. See :meth:`torch.Tensor.view` on when it is
    possible to return a view.
    
    See :func:`torch.reshape`
    
    Args:
        shape (tuple of ints or int...): the desired shape



### Auto gradients of tensor objects

In [146]:
x = torch.tensor([[2., -1.], [1., 1.]], requires_grad=True, dtype=torch.float32)
print(x)

tensor([[ 2., -1.],
        [ 1.,  1.]], requires_grad=True)


In [155]:
x_pow = x.pow(2)
print(x_pow)

out = x_pow.sum()
print(out)

tensor([[4., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)
tensor(7., grad_fn=<SumBackward0>)


In [156]:
out.backward()

In [178]:
x = torch.rand(1, 500)
y = torch.rand(500, 700)

In [179]:
x_cuda, y_cuda = x.to(device), y.to(device)

In [180]:
x_cuda, y_cuda

(tensor([[1.6893e-01, 1.2702e-01, 6.3977e-01, 4.8693e-01, 6.6883e-01, 5.2767e-01,
          2.9266e-01, 4.8771e-01, 4.0668e-02, 7.2024e-01, 6.3549e-01, 3.8948e-02,
          7.7164e-01, 5.2639e-01, 2.1093e-01, 3.5002e-02, 4.6697e-01, 1.4309e-01,
          3.0893e-01, 5.6080e-01, 7.2982e-01, 1.5240e-01, 8.9344e-01, 3.4833e-01,
          2.8919e-01, 1.8048e-01, 4.0390e-01, 3.5767e-01, 1.8823e-01, 5.2853e-01,
          8.6416e-01, 6.1343e-01, 1.5101e-01, 3.2771e-01, 4.1272e-01, 9.3814e-01,
          9.7716e-01, 1.8983e-01, 8.9514e-01, 2.5325e-01, 7.3271e-02, 2.0170e-01,
          5.9299e-01, 3.3890e-01, 1.0264e-01, 6.8640e-01, 6.0104e-01, 6.7730e-01,
          4.4060e-01, 1.4742e-01, 3.9271e-01, 4.6176e-02, 8.2724e-02, 4.7608e-01,
          6.1529e-01, 1.5224e-01, 3.4442e-01, 7.1615e-01, 2.5812e-01, 1.2411e-01,
          2.1141e-01, 8.6101e-01, 8.1167e-01, 7.5149e-01, 3.6057e-01, 2.9602e-01,
          2.4711e-01, 5.3215e-01, 1.3992e-01, 2.1833e-01, 8.5877e-01, 4.9608e-01,
          9.0846

In [199]:
%timeit z = (x_cuda @ y_cuda)

42.7 µs ± 3.86 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [182]:
x_cpu, y_cpu = x.cpu(), y.cpu()

In [183]:
x_cpu, y_cpu

(tensor([[1.6893e-01, 1.2702e-01, 6.3977e-01, 4.8693e-01, 6.6883e-01, 5.2767e-01,
          2.9266e-01, 4.8771e-01, 4.0668e-02, 7.2024e-01, 6.3549e-01, 3.8948e-02,
          7.7164e-01, 5.2639e-01, 2.1093e-01, 3.5002e-02, 4.6697e-01, 1.4309e-01,
          3.0893e-01, 5.6080e-01, 7.2982e-01, 1.5240e-01, 8.9344e-01, 3.4833e-01,
          2.8919e-01, 1.8048e-01, 4.0390e-01, 3.5767e-01, 1.8823e-01, 5.2853e-01,
          8.6416e-01, 6.1343e-01, 1.5101e-01, 3.2771e-01, 4.1272e-01, 9.3814e-01,
          9.7716e-01, 1.8983e-01, 8.9514e-01, 2.5325e-01, 7.3271e-02, 2.0170e-01,
          5.9299e-01, 3.3890e-01, 1.0264e-01, 6.8640e-01, 6.0104e-01, 6.7730e-01,
          4.4060e-01, 1.4742e-01, 3.9271e-01, 4.6176e-02, 8.2724e-02, 4.7608e-01,
          6.1529e-01, 1.5224e-01, 3.4442e-01, 7.1615e-01, 2.5812e-01, 1.2411e-01,
          2.1141e-01, 8.6101e-01, 8.1167e-01, 7.5149e-01, 3.6057e-01, 2.9602e-01,
          2.4711e-01, 5.3215e-01, 1.3992e-01, 2.1833e-01, 8.5877e-01, 4.9608e-01,
          9.0846

In [200]:
%timeit z=(x_cpu @ y_cpu)

81.2 µs ± 13.3 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [197]:
import numpy as np
x_np = np.random.random((1, 500))
y_np = np.random.random((500, 700))

In [198]:
%timeit z = np.matmul(x_np, y_np)

469 µs ± 46.8 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [214]:
x_cuda.dtype

torch.float32

In [216]:
x_cuda.type(torch.float16).dtype

torch.float16